@startuml
!theme plain
actor User
participant "Frontend" as FE
participant "Backend Gateway" as BG
participant ":GatewayController" as GC
participant "Restaurant Service" as RS
participant ":RestaurantController" as RS2
participant "BDD Service" as BDD
participant ":RestaurantController" as BDD2
participant ":RestaurantDAO" as RDAO

User -> FE : Navigate to Home Page
activate FE

FE -> BG : GET /restaurants/all
activate BG

BG -> GC : getAllRestaurants()
activate GC

GC -> RS : GET /restaurants/all
activate RS

RS -> RS2: getAllRestaurants()
activate RS2

RS2 -> BDD : GET /database/restaurants/all
activate BDD

BDD -> BDD2 : getAllRestaurants()
activate BDD2

BDD2 -> RDAO : getAllRestaurants()
activate RDAO

RDAO --> BDD2 : List<Restaurant>
deactivate RDAO

BDD2 --> BDD : List<RestaurantDTO>
deactivate BDD2

BDD --> RS2 : List<RestaurantDTO>
deactivate BDD

RS2 --> RS : List<RestaurantDTO>
deactivate RS

RS --> GC : List<RestaurantDTO>
deactivate RS

GC --> BG : List<RestaurantDTO>
deactivate GC

BG --> FE : List<Restaurants>
deactivate BG

FE --> User : Display Restaurants
deactivate FE
@enduml
